######################################################################
# Automatically generated by qmake (3.0) ?? ?? 24 22:01:06 2016
######################################################################

TEMPLATE = app
TARGET = GluttonousSnake
INCLUDEPATH += .
QT+=gui widgets core

include(public.pri)

# Input
HEADERS += *.h
SOURCES += *.cpp
