######################################################################
# Automatically generated by qmake (3.0) ?? ?? 24 22:01:06 2016
######################################################################

TEMPLATE = app
TARGET = GluttonousSnake
INCLUDEPATH += .

# Input
HEADERS += GluttonousSnake.h
FORMS += GluttonousSnake.ui
SOURCES += GluttonousSnake.cpp main.cpp
RESOURCES += GluttonousSnake.qrc
